# Generated by Django 3.2.5 on 2022-05-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music_prefer',
            old_name='userpk',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Like_song',
        ),
    ]
