# Generated by Django 3.2.5 on 2022-06-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song_num',
        ),
        migrations.AddField(
            model_name='playlist',
            name='track',
            field=models.CharField(default=None, max_length=200, verbose_name='곡 번호'),
            preserve_default=False,
        ),
    ]
