# Generated by Django 3.2.5 on 2022-06-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220602_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='lyrics',
            field=models.TextField(default=None, verbose_name='가사'),
            preserve_default=False,
        ),
    ]
