# Generated by Django 3.2.5 on 2022-06-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.IntegerField(verbose_name='의도')),
                ('emotion', models.IntegerField(null=True, verbose_name='감정')),
                ('ner', models.CharField(max_length=100, null=True, verbose_name='개체명')),
                ('answer', models.TextField(verbose_name='대답')),
                ('answer_image', models.CharField(max_length=200, null=True, verbose_name='대답이미지')),
            ],
            options={
                'verbose_name': '챗봇',
                'verbose_name_plural': '챗봇(들)',
                'db_table': 'mango_train_data',
            },
        ),
    ]
